## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

 Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 0

If students address the detailed feedback in a future checkpoint they will earn these points back






|                                  | **Unsatisfactory**                                                                                                                                                                                                                                                                                                                        | **Developing**                                                                                                                                                                                                       | **Proficient**                                                                                                                                                                                            | **Excellent**                                                                                                                                                                            |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **EDA relevance**                | EDA is mostly neither relevant to the question nor helpful in figuring out how to address the question. Or the EDA does address the question, but many obviously relevant variables / analyses / figures were not included. | EDA is partly irrelevant/unhelpful. EDA missed one or two obvioulsy relevant analysis (distributions of single variables or relationships between variables) | EDA includes the obviously relevant / helpful variables in addressing the question.                                                              | Thorough EDA fully explored the dataset                                                                                                                 |
| **EDA analysis and description** | Many of the analyses are poor choices (e.g., using means instead of medians for obviously skewed data), or are poorly described in the text, or do not aid understanding the data                                                                                                                                                     | Some of the analyses are poor choices, or are poorly described in the text, or do not aid understanding the data                                                                                                 | All analyses are correct choices. Only one or two have minor issues in the text descriptions supporting them. Mostly they fit well with other elements of the EDA and support understanding the data  | All analyses are correct choices with clear text descriptions supporting them. The figures fit well with the other elements of the EDA, producing a clear understanding of the data. |
| **EDA figures**                  | Many of the figures are poor plot choices (e.g., using a bar plot to represent a time series where it would be better to use a line plot) or have poor aesthetics (including colormap, data point shape/color, axis labels, titles, annotations, text legibility) or do not aid understanding the data                                | Some of the figures are poor plot choices or have poor aesthetics. Some figures do not aid understanding the data                                                                                                | All figures are correct plot choices. Only one or two have minor questionable aesthetic choices. The figures mostly fit well with the other elements of the EDA and support understanding the data    | All figures are correct plot choices with beautiful aesthetics. The figures fit well with the other elements of the EDA, producing a clear understanding of the data.                |

# COGS 108 - EDA Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

# Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

# Hypothesis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Data

### Data overview

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your data checkpoint feedback

In [1]:
# Imports and Setup
import pandas as pd
import numpy as np
import os

RAW_DATA_DIR = 'data/00-raw/'
INT_DATA_DIR = 'data/01-interim/'
PROCESSED_DATA_DIR = 'data/02-processed/'

In [2]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [3]:
# Setup code -- Run only once after cloning!!! 
#
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    {
        'url': 'https://archive.ics.uci.edu/static/public/697/predict+students+dropout+and+academic+success.zip',
        'filename': 'predict_students_dropout.zip'
    },
    { 
        'url': 'https://zenodo.org/records/17239943/files/dataset_2022_hash.zip?download=1', 
        'filename':'university_dropout_2022.zip'
    } # Decompressed later using pd.read_csv
]
get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading predict_students_dropout.zip: 0.00B [00:00, ?B/s]

Successfully downloaded: predict_students_dropout.zip

Downloading university_dropout_2022.zip:   0%|          | 0.00/15.1M [00:00<?, ?B/s]
Downloading university_dropout_2022.zip:   0%|          | 11.3k/15.1M [00:00<03:14, 77.7kB/s]
Downloading university_dropout_2022.zip:   0%|          | 41.0k/15.1M [00:00<01:38, 153kB/s]
Downloading university_dropout_2022.zip:   1%|          | 94.2k/15.1M [00:00<00:59, 251kB/s]
Downloading university_dropout_2022.zip:   2%|▏         | 229k/15.1M [00:00<00:28, 521kB/s]
Downloading university_dropout_2022.zip:   3%|▎         | 484k/15.1M [00:00<00:15, 967kB/s]
Downloading university_dropout_2022.zip:   6%|▋         | 975k/15.1M [00:00<00:07, 1.79MB/s]
Downloading university_dropout_2022.zip:   9%|▉         | 1.43M/15.1M [00:01<00:06, 2.21MB/s]
Downloading university_dropout_2022.zip:  20%|██        | 3.07M/15.1M [00:01<00:02, 5.06MB/s]
Downloading university_dropout_2022.zip:  24%|██▍       | 3.69M/15.1M [00:01<00:02, 4.85MB/s]
Downloading university_dropout_2022.zip:  32%|███▏      | 4.77M/15.1M [00:01<00:01, 5.65MB/s]
Downloading university_dropout_2022.zip:  35%|███▌      | 5.33M/15.1M [00:01<00:01, 5.06MB/s]
Downloading university_dropout_2022.zip:  39%|███▊      | 5.84M/15.1M [00:01<00:02, 4.59MB/s]
Downloading university_dropout_2022.zip:  42%|████▏     | 6.30M/15.1M [00:01<00:02, 4.06MB/s]
Downloading university_dropout_2022.zip:  44%|████▍     | 6.71M/15.1M [00:02<00:02, 3.70MB/s]
Downloading university_dropout_2022.zip:  47%|████▋     | 7.08M/15.1M [00:02<00:02, 3.08MB/s]
Downloading university_dropout_2022.zip:  49%|████▉     | 7.40M/15.1M [00:02<00:03, 2.37MB/s]
Downloading university_dropout_2022.zip:  51%|█████     | 7.66M/15.1M [00:02<00:03, 2.25MB/s]
Downloading university_dropout_2022.zip:  52%|█████▏    | 7.90M/15.1M [00:02<00:03, 1.92MB/s]
Downloading university_dropout_2022.zip:  54%|█████▎    | 8.10M/15.1M [00:03<00:04, 1.54MB/s]
Downloading university_dropout_2022.zip:  55%|█████▍    | 8.28M/15.1M [00:03<00:04, 1.47MB/s]
Downloading university_dropout_2022.zip:  56%|█████▌    | 8.50M/15.1M [00:03<00:04, 1.46MB/s]
Downloading university_dropout_2022.zip:  57%|█████▋    | 8.69M/15.1M [00:03<00:04, 1.44MB/s]
Downloading university_dropout_2022.zip:  59%|█████▉    | 8.91M/15.1M [00:03<00:04, 1.44MB/s]
Downloading university_dropout_2022.zip:  60%|██████    | 9.10M/15.1M [00:03<00:04, 1.43MB/s]
Downloading university_dropout_2022.zip:  62%|██████▏   | 9.31M/15.1M [00:03<00:04, 1.43MB/s]
Downloading university_dropout_2022.zip:  63%|██████▎   | 9.53M/15.1M [00:04<00:03, 1.44MB/s]
Downloading university_dropout_2022.zip:  64%|██████▍   | 9.74M/15.1M [00:04<00:03, 1.45MB/s]
Downloading university_dropout_2022.zip:  66%|██████▌   | 9.95M/15.1M [00:04<00:03, 1.46MB/s]
Downloading university_dropout_2022.zip:  67%|██████▋   | 10.1M/15.1M [00:04<00:03, 1.31MB/s]
Downloading university_dropout_2022.zip:  68%|██████▊   | 10.3M/15.1M [00:04<00:03, 1.38MB/s]
Downloading university_dropout_2022.zip:  69%|██████▉   | 10.5M/15.1M [00:04<00:03, 1.29MB/s]
Downloading university_dropout_2022.zip:  70%|███████   | 10.6M/15.1M [00:04<00:03, 1.22MB/s]
Downloading university_dropout_2022.zip:  71%|███████▏  | 10.8M/15.1M [00:05<00:04, 912kB/s]
Downloading university_dropout_2022.zip:  73%|███████▎  | 11.1M/15.1M [00:05<00:03, 1.16MB/s]
Downloading university_dropout_2022.zip:  74%|███████▍  | 11.2M/15.1M [00:05<00:03, 1.09MB/s]
Downloading university_dropout_2022.zip:  75%|███████▍  | 11.3M/15.1M [00:05<00:03, 1.01MB/s]
Downloading university_dropout_2022.zip:  75%|███████▌  | 11.4M/15.1M [00:05<00:03, 949kB/s]
Downloading university_dropout_2022.zip:  76%|███████▌  | 11.5M/15.1M [00:05<00:03, 920kB/s]
Downloading university_dropout_2022.zip:  77%|███████▋  | 11.6M/15.1M [00:06<00:04, 816kB/s]
Downloading university_dropout_2022.zip:  78%|███████▊  | 11.8M/15.1M [00:06<00:04, 842kB/s]
Downloading university_dropout_2022.zip:  78%|███████▊  | 11.8M/15.1M [00:06<00:04, 785kB/s]
Downloading university_dropout_2022.zip:  79%|███████▉  | 11.9M/15.1M [00:06<00:04, 729kB/s]
Downloading university_dropout_2022.zip:  79%|███████▉  | 12.0M/15.1M [00:06<00:04, 712kB/s]
Downloading university_dropout_2022.zip:  80%|████████  | 12.1M/15.1M [00:06<00:04, 698kB/s]
Downloading university_dropout_2022.zip:  81%|████████  | 12.2M/15.1M [00:06<00:04, 693kB/s]
Downloading university_dropout_2022.zip:  81%|████████▏ | 12.3M/15.1M [00:07<00:04, 694kB/s]
Downloading university_dropout_2022.zip:  82%|████████▏ | 12.4M/15.1M [00:07<00:03, 690kB/s]
Downloading university_dropout_2022.zip:  83%|████████▎ | 12.5M/15.1M [00:07<00:03, 755kB/s]
Downloading university_dropout_2022.zip:  83%|████████▎ | 12.6M/15.1M [00:07<00:03, 759kB/s]
Downloading university_dropout_2022.zip:  84%|████████▎ | 12.7M/15.1M [00:07<00:03, 755kB/s]
Downloading university_dropout_2022.zip:  84%|████████▍ | 12.8M/15.1M [00:07<00:03, 688kB/s]
Downloading university_dropout_2022.zip:  85%|████████▍ | 12.8M/15.1M [00:07<00:03, 687kB/s]
Downloading university_dropout_2022.zip:  86%|████████▌ | 12.9M/15.1M [00:07<00:03, 693kB/s]
Downloading university_dropout_2022.zip:  86%|████████▌ | 13.0M/15.1M [00:08<00:02, 761kB/s]
Downloading university_dropout_2022.zip:  87%|████████▋ | 13.1M/15.1M [00:08<00:02, 769kB/s]
Downloading university_dropout_2022.zip:  87%|████████▋ | 13.2M/15.1M [00:08<00:02, 772kB/s]
Downloading university_dropout_2022.zip:  88%|████████▊ | 13.3M/15.1M [00:08<00:02, 710kB/s]
Downloading university_dropout_2022.zip:  88%|████████▊ | 13.4M/15.1M [00:08<00:02, 682kB/s]
Downloading university_dropout_2022.zip:  89%|████████▉ | 13.5M/15.1M [00:08<00:02, 713kB/s]
Downloading university_dropout_2022.zip:  90%|████████▉ | 13.6M/15.1M [00:08<00:02, 707kB/s]
Downloading university_dropout_2022.zip:  90%|█████████ | 13.7M/15.1M [00:08<00:01, 728kB/s]
Downloading university_dropout_2022.zip:  91%|█████████ | 13.8M/15.1M [00:09<00:01, 715kB/s]
Downloading university_dropout_2022.zip:  92%|█████████▏| 13.9M/15.1M [00:09<00:01, 734kB/s]
Downloading university_dropout_2022.zip:  93%|█████████▎| 14.0M/15.1M [00:09<00:01, 723kB/s]
Downloading university_dropout_2022.zip:  93%|█████████▎| 14.1M/15.1M [00:09<00:01, 636kB/s]
Downloading university_dropout_2022.zip:  93%|█████████▎| 14.1M/15.1M [00:09<00:01, 580kB/s]
Downloading university_dropout_2022.zip:  94%|█████████▍| 14.3M/15.1M [00:09<00:01, 676kB/s]
Downloading university_dropout_2022.zip:  95%|█████████▍| 14.3M/15.1M [00:09<00:01, 624kB/s]
Downloading university_dropout_2022.zip:  95%|█████████▌| 14.4M/15.1M [00:10<00:01, 600kB/s]
Downloading university_dropout_2022.zip:  96%|█████████▌| 14.5M/15.1M [00:10<00:01, 590kB/s]
Downloading university_dropout_2022.zip:  96%|█████████▋| 14.6M/15.1M [00:10<00:00, 607kB/s]
Downloading university_dropout_2022.zip:  97%|█████████▋| 14.7M/15.1M [00:10<00:00, 602kB/s]
Downloading university_dropout_2022.zip:  98%|█████████▊| 14.8M/15.1M [00:10<00:00, 620kB/s]
Downloading university_dropout_2022.zip:  98%|█████████▊| 14.9M/15.1M [00:10<00:00, 609kB/s]
Downloading university_dropout_2022.zip:  99%|█████████▉| 15.0M/15.1M [00:11<00:00, 630kB/s]
Downloading university_dropout_2022.zip:  99%|█████████▉| 15.1M/15.1M [00:11<00:00, 641kB/s]
Overall Download Progress: 100%|██████████| 2/2 [00:12<00:00,  6.02s/it]

Successfully downloaded: university_dropout_2022.zip

### Dataset #1 

Instructions: REPLACE the contents of this cell and the one below with your work, including any updates to recover points lost in your data checkpoint feedback

In [4]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

In [5]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## 3.A LOAD DATASET
data1 = pd.read_csv(
    f'{RAW_DATA_DIR}predict_students_dropout.zip',
    sep=';',
    compression='zip' # Webpage download default as .zip
)

In [6]:
## 3.B MAKE TIDY OR SHOW TIDY
data1.head(5)

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,...,Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,...,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,...,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,...,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,...,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,...,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [7]:
## 3.C DEMONSTRATE SIZE OF DATASET
print("Dataset shape (rows, columns):", data1.shape)
data1.dtypes

Dataset shape (rows, columns): (4424, 37)

Marital status                                      int64
Application mode                                    int64
Application order                                   int64
Course                                              int64
Daytime/evening attendance\t                        int64
Previous qualification                              int64
Previous qualification (grade)                    float64
Nacionality                                         int64
Mother's qualification                              int64
Father's qualification                              int64
Mother's occupation                                 int64
Father's occupation                                 int64
Admission grade                                   float64
Displaced                                           int64
Educational special needs                           int64
Debtor                                              int64
Tuition fees up to date                             int64
Gender                                              int64
Scholarship holder                                  int64
Age at enrollment                                   int64
International                                       int64
Curricular units 1st sem (credited)                 int64
Curricular units 1st sem (enrolled)                 int64
Curricular units 1st sem (evaluations)              int64
Curricular units 1st sem (approved)                 int64
Curricular units 1st sem (grade)                  float64
Curricular units 1st sem (without evaluations)      int64
Curricular units 2nd sem (credited)                 int64
Curricular units 2nd sem (enrolled)                 int64
Curricular units 2nd sem (evaluations)              int64
Curricular units 2nd sem (approved)                 int64
Curricular units 2nd sem (grade)                  float64
Curricular units 2nd sem (without evaluations)      int64
Unemployment rate                                 float64
Inflation rate                                    float64
GDP                                               float64
Target                                             object
dtype: object

**This data set was already used for more formal projects and has already been cleaned of missing values.**

In [8]:
## 3.D FIND OUT HOW MUCH DATA IS MISSING AND WHERE
col_missing_count = data1.isnull().sum()
total_missing_count = col_missing_count.sum()
total_missing_count
print(f"There are {total_missing_count} missing values.")

There are 0 missing values.

In [9]:
## 3.E FIND AND FLAG ANY OUTLIERS OR SUS ENTRIES
numeric_cols = data1.select_dtypes(include = ['number']).columns
outliers = pd.DataFrame(index = data1.index)
## iterate accross all numeric columns and find outliers and store in outliers df
for col in numeric_cols:
    ##https://stackoverflow.com/questions/23228244/how-do-you-find-the-iqr-in-numpy
    q75, q25 = np.nanpercentile(data1[col], [75, 25])
    iqr = q75 - q25
    lower_bound = q25 - 1.5 * iqr
    upper_bound = q75 + 1.5 * iqr
    outliers[f'{col}_outlier'] = (data1[col] < lower_bound) | (data1[col] > upper_bound)

print('Number of outliers in each column')
print(outliers.sum())

Number of outliers in each column
Marital status_outlier                                     505
Application mode_outlier                                     0
Application order_outlier                                  541
Course_outlier                                             442
Daytime/evening attendance\t_outlier                       483
Previous qualification_outlier                             707
Previous qualification (grade)_outlier                     179
Nacionality_outlier                                        110
Mother's qualification_outlier                               0
Father's qualification_outlier                               0
Mother's occupation_outlier                                182
Father's occupation_outlier                                177
Admission grade_outlier                                     86
Displaced_outlier                                            0
Educational special needs_outlier                           51
Debtor_outlier                                             503
Tuition fees up to date_outlier                            528
Gender_outlier                                               0
Scholarship holder_outlier                                1099
Age at enrollment_outlier                                  441
International_outlier                                      110
Curricular units 1st sem (credited)_outlier                577
Curricular units 1st sem (enrolled)_outlier                424
Curricular units 1st sem (evaluations)_outlier             158
Curricular units 1st sem (approved)_outlier                180
Curricular units 1st sem (grade)_outlier                   726
Curricular units 1st sem (without evaluations)_outlier     294
Curricular units 2nd sem (credited)_outlier                530
Curricular units 2nd sem (enrolled)_outlier                369
Curricular units 2nd sem (evaluations)_outlier             109
Curricular units 2nd sem (approved)_outlier                 44
Curricular units 2nd sem (grade)_outlier                   877
Curricular units 2nd sem (without evaluations)_outlier     282
Unemployment rate_outlier                                    0
Inflation rate_outlier                                       0
GDP_outlier                                                  0
dtype: int64

**This data is already very clean, no missing values or ridiculous outliers, the only thing that we may have to change is the data types being used for certain variables**

In [10]:
## 3.F CLEAN THE DATA
if data1.isna().sum().sum() == 0:
    print('No missing values')
else: 
    print(f'There are {data1.isna().sum().sum()} missin values')

No missing values

In [11]:
## Next need to remove columns that we do not need
cols_to_drop = [
    'Marital status',  # Demographics
    'Application mode', # Application related
    'Application order', # Application related
    'Course', # Student "Major"
    'Daytime/evening attendance\t', # Unnecessary and no equivalent in data2
    'Previous qualification', # Students highest level of education
    'Nacionality', # Demographics
    "Mother's qualification", "Father's qualification", "Mother's occupation", "Father's occupation", # Family Demographics
    'Displaced', 'Educational special needs', 'Debtor', 'Tuition fees up to date', 'Scholarship holder', # Unnecessary Student demographics
    'Age at enrollment', 'International', # Unnecessary Student demographics
    'Unemployment rate', 'Inflation rate', 'GDP', # Portugal Economic Data
]

data1 = data1.drop(columns = cols_to_drop, errors = 'ignore')

In [12]:
## Mapping 'Target' to numerical values
target_map = {
    'Dropout': 0,
    'Enrolled': 1,
    'Graduate': 2
}

data1['Target_Numeric'] = data1['Target'].map(target_map)
print(data1[['Target', 'Target_Numeric']].head(100))
## Target_numeric now shows the outcome as an integer

      Target  Target_Numeric
0    Dropout               0
1   Graduate               2
2    Dropout               0
3   Graduate               2
4   Graduate               2
..       ...             ...
95  Enrolled               1
96  Graduate               2
97  Graduate               2
98  Enrolled               1
99   Dropout               0

[100 rows x 2 columns]

In [13]:
## 3.G MOVE TO PROCESSED
data1_clean = data1.copy()
processed_path = os.path.join(PROCESSED_DATA_DIR, 'predict_students_dropout_clean.csv')
data1_clean.to_csv(processed_path, index=False, sep = ';')

In [14]:
## 4. SUMMARY STATISTICS
data1_clean.describe()

,Previous qualification (grade),Admission grade,Gender,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Target_Numeric
count,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000,4424.000000
mean,132.613314,126.978119,0.351718,0.709991,6.270570,8.299051,4.706600,10.640822,0.137658,0.541817,6.232143,8.063291,4.435805,10.230206,0.150316,1.178119
std,13.188332,14.482001,0.477560,2.360507,2.480178,4.179106,3.094238,4.843663,0.690880,1.918546,2.195951,3.947951,3.014764,5.210808,0.753774,0.888243
min,95.000000,95.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,125.000000,117.900000,0.000000,0.000000,5.000000,6.000000,3.000000,11.000000,0.000000,0.000000,5.000000,6.000000,2.000000,10.750000,0.000000,0.000000
50%,133.100000,126.100000,0.000000,0.000000,6.000000,8.000000,5.000000,12.285714,0.000000,0.000000,6.000000,8.000000,5.000000,12.200000,0.000000,1.000000
75%,140.000000,134.800000,1.000000,0.000000,7.000000,10.000000,6.000000,13.400000,0.000000,0.000000,7.000000,10.000000,6.000000,13.333333,0.000000,2.000000
max,190.000000,190.000000,1.000000,20.000000,26.000000,45.000000,26.000000,18.875000,12.000000,19.000000,23.000000,33.000000,20.000000,18.571429,12.000000,2.000000

### Dataset #2
 as above, add any more copies of this that you need to given how many datasets you have

In [15]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Results

### Exploratory Data Analysis

Instructions: replace the words in this subsection with whatever words you need to setup and preview the EDA you're going to do.   

Please explicitly load the fully wrangled data you will use from `data/02-processed`.  This is a good idea rather than forcing people to re-run the data getting / wrangling cells above.  Sometimes it takes a long time to get / wrangle data compared to reloading the fixed up dataset.

Carry out whatever EDA you need to for your project in the code cells below.  Because every project will be different we can't really give you much of a template at this point. But please make sure you describe the what and why in text here as well as providing interpretation of results and context.

Please note that you should consider the use of python modules in your work.  Any code which gets called repeatedly should be modularized. So if you run the same pre-processing, analysis or visualiazation on different subsets of the data, then you should turn that into a function or class.  Put that function or class in a .py file that lives in `modules/`.  Import the module you made and use it to get your work done.  For reference see `get_raw()` which is inside `modules/get_data.py`.

#### Section 1 of EDA - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [16]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION
data1_eda = pd.read_csv('data/02-processed/predict_students_dropout_clean.csv', sep=';')
data1_eda

,Previous qualification (grade),Admission grade,Gender,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Target,Target_Numeric
0,122.0,127.3,1,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0,Dropout,0
1,160.0,142.5,1,0,6,6,6,14.000000,0,0,6,6,6,13.666667,0,Graduate,2
2,122.0,124.8,1,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0,Dropout,0
3,122.0,119.6,0,0,6,8,6,13.428571,0,0,6,10,5,12.400000,0,Graduate,2
4,100.0,141.5,0,0,6,9,5,12.333333,0,0,6,6,6,13.000000,0,Graduate,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4419,125.0,122.2,1,0,6,7,5,13.600000,0,0,6,8,5,12.666667,0,Graduate,2
4420,120.0,119.0,0,0,6,6,6,12.000000,0,0,6,6,2,11.000000,0,Dropout,0
4421,154.0,149.5,0,0,7,8,7,14.912500,0,0,8,9,1,13.500000,0,Dropout,0
4422,180.0,153.8,0,0,5,5,5,13.800000,0,0,5,6,5,12.000000,0,Graduate,2
4423,152.0,152.0,0,0,6,8,6,11.666667,0,0,6,6,6,13.000000,0,Graduate,2

In [17]:
## Convert two GPA columsn to 4.0 scale for our understanding
## Also average GPAs over both semesters and add as a new column
max_port = 20.0
min_port = 0.0
max_usa = 4.0

grade_cols = [
    'Curricular units 1st sem (grade)',
    'Curricular units 2nd sem (grade)'
]

for col in grade_cols:
    data1_eda[col] = (data1_eda[col] / max_port) * max_usa

data1_eda['Avg_Gpa'] = (data1_eda['Curricular units 1st sem (grade)'] + data1_eda['Curricular units 2nd sem (grade)']) / 2

print(data1_eda[['Curricular units 1st sem (grade)','Curricular units 2nd sem (grade)', 'Avg_Gpa']].head(100))

   Previous qualification (grade)  Admission grade  Gender  \
0                           122.0            127.3       1
1                           160.0            142.5       1
2                           122.0            124.8       1
3                           122.0            119.6       0
4                           100.0            141.5       0
5                           133.1            114.8       1
6                           142.0            128.4       0
7                           119.0            113.1       1
8                           137.0            129.3       0
9                           138.0            123.0       0

   Curricular units 1st sem (credited)  Curricular units 1st sem (enrolled)  \
0                                    0                                    0
1                                    0                                    6
2                                    0                                    6
3                                    0                                    6
4                                    0                                    6
5                                    0                                    5
6                                    0                                    7
7                                    0                                    5
8                                    0                                    6
9                                    0                                    6

   Curricular units 1st sem (evaluations)  \
0                                       0
1                                       6
2                                       0
3                                       8
4                                       9
5                                      10
6                                       9
7                                       5
8                                       8
9                                       9

   Curricular units 1st sem (approved)  Curricular units 1st sem (grade)  \
0                                    0                          0.000000
1                                    6                          2.800000
2                                    0                          0.000000
3                                    6                          2.685714
4                                    5                          2.466667
5                                    5                          2.371429
6                                    7                          2.660000
7                                    0                          0.000000
8                                    6                          2.775000
9                                    5                          2.280000

   Curricular units 1st sem (without evaluations)  \
0                                               0
1                                               0
2                                               0
3                                               0
4                                               0
5                                               0
6                                               0
7                                               0
8                                               0
9                                               0

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    0
1                                    0                                    6
2                                    0                                    6
3                                    0                                    6
4                                    0                                    6
5                                    0                                    5
6                                    0                                    8
7                                    0                                    5
8                                    0                                    6
9                                    0                                    6

   Curricular units 2nd sem (evaluations)  \
0                                       0
1                                       6
2                                       0
3                                      10
4                                       6
5                                      17
6                                       8
7                                       5
8                                       7
9                                      14

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000
1                                    6                          2.733333
2                                    0                          0.000000
3                                    5                          2.480000
4                                    6                          2.600000
5                                    5                          2.300000
6                                    8                          2.869000
7                                    0                          0.000000
8                                    6                          2.828571
9                                    2                          2.700000

   Curricular units 2nd sem (without evaluations)    Target  Target_Numeric  \
0                                               0   Dropout               0
1                                               0  Graduate               2
2                                               0   Dropout               0
3                                               0  Graduate               2
4                                               0  Graduate               2
5                                               5  Graduate               2
6                                               0  Graduate               2
7                                               0   Dropout               0
8                                               0  Graduate               2
9                                               0   Dropout               0

   First Year GPA
0        0.000000
1        2.766667
2        0.000000
3        2.582857
4        2.533333
5        2.335714
6        2.764500
7        0.000000
8        2.801786
9        2.490000

#### Section 2 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [18]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them